### PR TITLE
Turning pages into a table

### PR DESCRIPTION
**Pull request by chelseybaker**
Includes #4, so that one should probably be reviewed and merged first :)

### CODE REVIEW

**Comment by stkent** [comment]
@chelseybaker can you rebase on master please? Thanks!

**Comment by stkent** [comment]
Functionality looks great! Some minor UI issues to fix:

1. When scrolling the list up and down, the text is clipped at the top and the bottom of the screen.
2. When scrolling the list up and down, the scrollbar overlaps the edge of the list instead of being aligned to the edge of the screen.
3. Dividers don't extend the full width of the screen (this is an Android standard, unlike the indented dividers you see on iOS).

vidcap 2016-06-17 at 16 00 00 pm

**Comment by stkent** [comment]
Uh oh, a crash!

Steps to reproduce:

- Launch app
- Enter any valid ZIP code
- Tap 'Find Location (List)' button
- Select any entry
- Rotate device

Stack trace is copied below; should be a 100% reliable reproduction though.

```
06-17 15:58:16.432 26996-26996/com.detroitlabs.chelseybaker.wundergroundweather E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                                  Process: com.detroitlabs.chelseybaker.wundergroundweather, PID: 26996
                                                                                                  java.lang.RuntimeException: Unable to start activity ComponentInfo{com.detroitlabs.chelseybaker.wundergroundweather/com.detroitlabs.chelseybaker.wundergroundweather.activities.WeatherDetailsActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.detroitlabs.chelseybaker.wundergroundweather.models.ForecastDay.getTitle()' on a null object reference
                                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
                                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
                                                                                                      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077)
                                                                                                      at android.app.ActivityThread.-wrap15(ActivityThread.java)
                                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350)
                                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                                      at android.os.Looper.loop(Looper.java:148)
                                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                                                      at java.lang.reflect.Method.invoke(Native Method)
                                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
                                                                                                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String com.detroitlabs.chelseybaker.wundergroundweather.models.ForecastDay.getTitle()' on a null object reference
                                                                                                      at com.detroitlabs.chelseybaker.wundergroundweather.fragements.ForecastDetailsPageFragment.onCreateView(ForecastDetailsPageFragment.java:37)
                                                                                                      at android.support.v4.app.Fragment.performCreateView(Fragment.java:1974)
                                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1252)
                                                                                                      at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1234)
                                                                                                      at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:2046)
                                                                                                      at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:174)
                                                                                                      at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:597)
                                                                                                      at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1237)
                                                                                                      at android.app.Activity.performStart(Activity.java:6268)
                                                                                                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2379)
                                                                                                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476) 
                                                                                                      at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4077) 
                                                                                                      at android.app.ActivityThread.-wrap15(ActivityThread.java) 
                                                                                                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1350) 
                                                                                                      at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                                                                      at android.os.Looper.loop(Looper.java:148) 
                                                                                                      at android.app.ActivityThread.main(ActivityThread.java:5417) 
                                                                                                      at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726) 
                                                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616) 
```

**Comment by chelseybaker** [comment]
Are you using a simulator for the first gif? And if so what are the specs on it? Because I don't see that in mine, there's no clipping it's all visible

**Comment by stkent** [comment]
Oops, that crash is on the next PR, my bad!

**Comment by stkent** [comment]
No, first gif is on my device.

**Comment by chelseybaker** [comment]
I adjusted the padding on the list, but I still can't don't see the problem where the text is clipped at the bottom. What kind of phone do you have?

**Comment by stkent** [comment]
@ Nexus 6 running Marshmallow; we have a very-similarly-specced test device (though I would expect this behavior to be device-and-API-level-independent...)

**Comment by stkent** [comment]
This looks good with the padding tweaks! For future reference, an option for applying top/bottom padding but allowing list content to show through it is exposed via the xml attribute [`clipToPadding`](https://developer.android.com/reference/android/view/ViewGroup.html#attr_android:clipToPadding).

**Pull request merged**
